
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[166] =
    {   0,
        0,    0,   46,   44,    1,    2,   44,   44,   30,   44,
       38,   39,   28,   26,   43,   27,   44,   29,   20,   20,
       42,   33,   37,   34,   16,   16,   16,   16,   16,   16,
       16,   16,   40,   44,   41,   35,    0,    3,   31,   18,
        0,   18,   22,    0,    0,    0,   20,   20,    0,   20,
       20,    0,   20,   25,   36,   24,    0,   16,   16,   16,
       16,   16,   16,   16,    7,   16,   16,   16,   16,   16,
       32,    0,   18,    0,   18,   22,   22,   22,   22,    0,
       23,    0,   18,   20,   20,   20,    0,   21,   20,   17,
       16,   10,   16,   16,   16,   16,    4,   16,   16,   16,

       16,    0,   18,   22,   22,   22,   22,    0,   23,   23,
       23,   23,    0,   18,    0,    0,    0,   21,   21,    0,
       21,   21,   21,   16,   11,    8,   16,   16,    6,   16,
       16,   16,    0,   18,   23,   23,   23,   23,    0,    0,
       21,   21,    0,   19,   21,   21,   16,   16,    5,   16,
       16,    9,    0,   19,   19,   16,   16,   16,   12,   13,
       15,   16,   16,   14,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   27,   26,   26,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
        1,    1,    1,    1,    1,    1,   35,   36,   37,   26,

       38,   39,   30,   40,   41,   30,   30,   42,   43,   44,
       45,   46,   30,   47,   48,   49,   50,   30,   51,   52,
       30,   30,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    1,    2,    1,    2,    1,    1,    3,    1,
        1,    1,    4,    1,    4,    5,    1,    6,    6,    6,
        6,    1,    1,    1,    1,    7,    7,    7,    7,    8,
        9,   10,   11,    8,    7,    7,    7,    7,    7,    8,
        8,    9,    8,    8,    8,   10,    8,    8,    8,   11,
        8,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[176] =
    {   0,
        0,    0,  423,  424,  424,  424,  398,  415,  424,  412,
      424,  424,  424,  424,  424,  424,   38,  424,   51,   95,
      424,  396,  394,  392,  399,   45,   46,   49,   58,   48,
       57,   52,  424,  358,  424,  424,  405,  424,  424,  137,
       89,  111,  171,  131,   57,  123,   86,  376,  386,  359,
      356,  142,    0,  424,  424,  424,    0,  381,   50,   61,
       84,   47,  132,  108,  376,   78,  123,  151,   65,  155,
      424,  163,    0,  197,  424,  141,  357,  329,  322,  187,
      205,  207,  247,  330,  424,  331,    0,  241,  319,  424,
      105,  342,  162,  157,  161,  184,  341,  178,  185,  181,

      187,  214,  283,  323,  424,  324,  311,  167,  206,  321,
      307,  305,  222,    0,  239,    0,  198,  284,  218,  239,
      314,  299,  296,  229,  321,  320,  230,  245,  317,  246,
      242,  237,  278,    0,  299,  424,  300,  227,  273,  275,
      231,  424,  275,  297,  232,  218,  265,  261,  243,  293,
      295,  177,  304,  309,  424,  304,  308,  307,  119,  109,
      106,  311,  313,  102,  424,  358,  365,  372,  373,  379,
      384,  393,  398,  402,  407
    } ;

static const flex_int16_t yy_def[176] =
    {   0,
      165,    1,  165,  165,  165,  165,  165,  166,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  167,  167,  167,  167,  167,  167,
      167,  167,  165,  165,  165,  165,  166,  165,  165,  165,
      165,   40,  165,  165,  165,  165,  165,  165,  168,  165,
      165,  165,   20,  165,  165,  165,  169,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      165,  165,   40,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  170,  171,  165,  165,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,

      167,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,   83,  172,  173,  170,  173,  165,  174,
      165,  165,  165,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  165,  103,  165,  165,  165,  165,  172,  172,
      165,  165,  174,  175,  165,  165,  167,  167,  167,  167,
      167,  167,  175,  175,  165,  167,  167,  167,  167,  167,
      167,  167,  167,  167,    0,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165
    } ;

static const flex_int16_t yy_nxt[480] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,    4,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   21,   22,   23,   24,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   26,   27,   28,   25,
       29,   25,   30,   25,   25,   25,   25,   31,   25,   25,
       32,   25,   33,   34,   35,   40,   40,   40,   40,   41,
       57,   57,   57,   57,   57,   57,   42,   57,   43,   43,
       43,   44,   57,   57,   81,   81,   57,   45,   46,   59,
       57,   47,   67,   48,   49,   60,   45,   62,   46,   61,
       64,   70,   50,   57,   94,   68,   65,   63,   91,   57,

       51,   66,   49,   52,   92,   69,   43,   43,   43,   44,
       42,  100,   53,   53,   53,   53,   84,   57,   85,  165,
       57,   57,   46,   57,   57,   47,   97,   48,   40,   40,
       40,   40,   46,   93,   57,   82,   50,   82,   57,   80,
       83,   83,   83,   83,   51,   72,   42,   57,   44,   44,
       44,   44,   96,  124,   73,   73,   73,   73,   46,   53,
       53,   53,   53,   98,   74,   75,   57,   75,   46,   95,
       57,  104,   57,  105,   74,   75,   57,   57,   75,   41,
       73,   73,   73,   73,   81,   81,   42,   99,   43,   43,
       43,   44,   57,   57,  126,  101,   57,  127,   46,   57,

       57,   76,   57,   77,   44,   44,   44,   44,   46,  102,
      125,  102,   78,  108,  103,  103,  103,  103,  128,  130,
       79,  129,   81,   81,   83,   83,   83,   83,  132,  120,
      131,  103,  103,  103,  103,  109,  135,  110,  136,  114,
      114,  114,  114,  120,   57,   57,  111,  139,  141,  116,
      142,  143,   57,  143,  112,  113,  117,   57,   57,  142,
       57,   57,  142,  142,  114,  114,  114,  114,  136,  147,
      120,  119,  120,  121,  152,   75,   57,   75,  151,  148,
       57,  165,  122,  139,  120,   75,  120,  165,   75,  165,
      123,  133,  116,  149,  150,  134,  134,  134,  134,  117,

      134,  134,  134,  134,  165,  153,  120,  156,   57,  157,
       57,   75,  165,   75,  119,  120,  121,  153,  165,   57,
      120,   75,   57,   57,   75,  122,   57,  155,   57,  120,
      136,  136,   57,  123,  165,   57,   57,  146,  155,  155,
      142,  158,  161,  159,  145,  165,  138,  162,  136,  160,
      155,  137,  105,  163,  105,  105,   57,   57,  164,   37,
       85,   85,   85,  107,   37,   37,   37,   37,   37,   58,
      105,   58,   58,   58,   58,   58,   88,   88,   88,   90,
       90,   90,   90,   90,  115,  115,  118,  106,  118,  118,
      118,   57,  118,  118,  118,  140,   57,   89,  140,  140,

       85,   87,  140,  118,  118,  144,   86,  144,  144,  154,
       38,   71,  154,  154,   57,  154,   56,   55,   54,   39,
       38,   36,  165,    3,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165
    } ;

static const flex_int16_t yy_chk[480] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   17,   17,   17,   17,   19,
       26,   27,   62,   30,   28,   59,   19,   32,   19,   19,
       19,   19,   31,   29,   45,   45,   60,   19,   19,   26,
       69,   19,   30,   19,   19,   26,   19,   27,   19,   26,
       28,   32,   19,   66,   62,   31,   29,   27,   59,   61,

       19,   29,   19,   20,   60,   31,   41,   41,   41,   41,
       20,   69,   20,   20,   20,   20,   47,  164,   47,   42,
       91,  161,   20,   64,  160,   20,   66,   20,   42,   42,
       42,   42,   20,   61,  159,   46,   20,   46,   67,   44,
       46,   46,   46,   46,   20,   40,   44,   63,   44,   44,
       44,   44,   64,   91,   40,   40,   40,   40,   44,   52,
       52,   52,   52,   67,   40,   40,   68,   40,   44,   63,
       70,   76,   94,   76,   40,   40,   95,   93,   40,   43,
       72,   72,   72,   72,  108,  108,   43,   68,   43,   43,
       43,   43,  152,   98,   94,   70,  100,   95,   43,   96,

       99,   43,  101,   43,   80,   80,   80,   80,   43,   74,
       93,   74,   43,   81,   74,   74,   74,   74,   96,   99,
       43,   98,   81,   81,   82,   82,   82,   82,  101,  117,
      100,  102,  102,  102,  102,   81,  109,   81,  109,  113,
      113,  113,  113,  117,  124,  127,   81,  115,  119,   88,
      119,  120,  132,  120,   81,   83,   88,  131,  149,  146,
      128,  130,  145,  141,   83,   83,   83,   83,  138,  124,
      115,   88,   88,   88,  132,   83,  148,   83,  131,  127,
      147,  139,   88,  140,  115,   83,   88,  143,   83,  143,
       88,  103,  118,  128,  130,  133,  133,  133,  133,  118,

      103,  103,  103,  103,  139,  144,  140,  147,  150,  148,
      151,  103,  153,  103,  118,  118,  118,  154,  139,  156,
      140,  103,  158,  157,  103,  118,  162,  144,  163,  118,
      137,  135,  129,  118,  153,  126,  125,  123,  144,  154,
      122,  150,  157,  151,  121,  153,  112,  158,  111,  156,
      154,  110,  107,  162,  106,  104,   97,   92,  163,  166,
       89,   86,   84,   79,  166,  166,  166,  166,  166,  167,
       78,  167,  167,  167,  167,  167,  168,  168,  168,  169,
      169,  169,  169,  169,  170,  170,  171,   77,  171,  171,
      171,   65,  171,  171,  171,  172,   58,   51,  172,  172,

       50,   49,  172,  173,  173,  174,   48,  174,  174,  175,
       37,   34,  175,  175,   25,  175,   24,   23,   22,   10,
        8,    7,    3,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analizator.l"
#line 3 "analizator.l"
    /*
        comenzi:
            - flex analizator.l
            - gcc lex.yy.c -o exe
            - ./exe sau ./exe <test.c
        text copiat in fisierul generat
        incluziuni de fisiere, variabile globale 
    */

    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include "analizator_s.tab.h"
    
    struct Node {
        char val[101];
        int poz;
        struct Node *left;
        struct Node *right;
    };

    typedef struct {
        char atom[101];
        int poz;
    } Element;

    typedef struct {
        int poz_normala;
        int poz_speciala;
    } FIP_Element;

    struct Node* newNode(char* val, int poz) {
        struct Node* temp = (struct Node*)malloc(sizeof(struct Node));
        strcpy(temp->val, val);
        temp->poz = poz;
        temp->left = temp->right = NULL;
        return temp;
    }

    struct Node* insert(struct Node* node, char* val, int poz) {
        if (node == NULL)
            return newNode(val, poz);
 
        if (strcmp(val, node->val) < 0)
            node->left = insert(node->left, val, poz);
        else if (strcmp(val, node->val) > 0)
            node->right = insert(node->right, val, poz);
    
        return node;
    }

    // Stanga Radacina Dreapta
    void inorder(struct Node* root) {
        if (root != NULL) {
            inorder(root->left);
            printf("Valoare: %s Pozitie: %d\n", root->val, root->poz);
            inorder(root->right);
        }
    }

    struct Node* search(struct Node* root, char* val) {
        if (root == NULL || strcmp(root->val, val) == 0)
            return root;
        
        if (strcmp(root->val, val) < 0)
            return search(root->right, val);
    
        return search(root->left, val);
    }

    int line_ct = 1;

    struct Node* TS_ID = NULL;
    int TS_ID_CT = 1000;
    struct Node* TS_CONST = NULL;
    int TS_CONST_CT = 2000;

    Element atomi[1001];
    int atomi_ct = 34;

    FIP_Element FIP[1001];
    int fip_ct = 0;

    char error[1001] = "";

    int cautaAtom(char* atom) {
        for (int i = 0; i < atomi_ct; i++) {
            if (strcmp(atomi[i].atom, atom) == 0)
                return 1;
        }

        return 0;
    }

    int cautInAtomi(char* atom) {
        int result = -1;
        for(int i = 0; i < atomi_ct; i++) {
            if (strcmp(atomi[i].atom, atom) == 0) {
                result = atomi[i].poz;
            }
        }
        return result;
    }

    void addAtom(int rand, char* atom, char* tip, int poz) {
        if (strcmp(tip, "Cuvant rezervat") == 0 || strcmp(tip, "Operator") == 0 || strcmp(tip, "Separator") == 0) {
            if (cautaAtom(atom) == 0) {
                strcpy(atomi[poz].atom, atom);
                atomi[poz].poz = poz;
                atomi_ct += 1;
            }
            // adauga in FIP
            FIP[fip_ct].poz_normala = cautInAtomi(atom);
            FIP[fip_ct].poz_speciala = -1;
            fip_ct += 1;
        } else {
            if (strcmp(tip, "Variabila") == 0) {
                strcpy(atomi[poz].atom, "ID");
                atomi[poz].poz = 0;

                if (strlen(atom) <= 8) {
                    if (TS_ID == NULL) {
                        //printf("Sunt in id - primul element\n");
                        TS_ID = insert(TS_ID, atom, TS_ID_CT);
                        TS_ID_CT += 1;
                    } else if (search(TS_ID, atom) == NULL) {
                        //printf("Sunt in id - alt element\n");
                        insert(TS_ID, atom, TS_ID_CT);
                        TS_ID_CT += 1;
                    }
                    // Adauga in FIP
                    FIP[fip_ct].poz_normala = 0;
                    FIP[fip_ct].poz_speciala = search(TS_ID, atom)->poz;
                    fip_ct += 1;
                } else {
                    // Arunca eroarea
                    //printf("Eroareeeeeee---------\n");
                    char intermediar[101] = "Lungimea variabilei ";
                    strcat(intermediar, atom);
                    strcat(intermediar, " pe linia ");
                    char cif[5];
                    sprintf(cif, "%d", rand);
                    strcat(intermediar, cif);
                    strcat(intermediar, " este mai mare decat 8!\n");
                    strcat(error, intermediar);
                }
            } else if (strcmp(tip, "Constanta") == 0) {
                strcpy(atomi[poz].atom, "CONST");
                atomi[poz].poz = 1;

                if (TS_CONST == NULL) {
                    //printf("Sunt in constanta - primul element\n");
                    TS_CONST = insert(TS_CONST, atom, TS_CONST_CT);
                    TS_CONST_CT += 1;
                } else if (search(TS_CONST, atom) == NULL) {
                    //printf("Sunt in constanta - alt element\n");
                    insert(TS_CONST, atom, TS_CONST_CT);
                    TS_CONST_CT += 1;
                }
                // Adauga in FIP
                FIP[fip_ct].poz_normala = 1;
                FIP[fip_ct].poz_speciala = search(TS_CONST, atom)->poz;
                fip_ct += 1;
            } else {
                // Arunca eroarea
                //printf("Eroareeeeeee---------\n");
                char intermediar[101] = "Atomul ";
                    strcat(intermediar, atom);
                    strcat(intermediar, " pe linia ");
                    char cif[5];
                    sprintf(cif, "%d", rand);
                    strcat(intermediar, cif);
                    strcat(intermediar, " nu apartine limbajului!\n");
                    strcat(error, intermediar);
            }
        }
    }
#line 782 "lex.yy.c"
/* definitii */
#line 784 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 188 "analizator.l"

#line 1003 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 166 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 424 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 189 "analizator.l"
/* ignoram white spaces */
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 190 "analizator.l"
line_ct++;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 191 "analizator.l"
{
                        printf("%d ~ %s ~ Constanta\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Constanta", 1);
                        return CONST_STRING;
                    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 196 "analizator.l"
{
                        printf("%d ~ int ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "int", "Cuvant rezervat", 2);
                        return INT;
                    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 201 "analizator.l"
{
                        printf("%d ~ float ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "float", "Cuvant rezervat", 3);
                        return FLOAT;
                    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 206 "analizator.l"
{
                        printf("%d ~ main ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "main", "Cuvant rezervat", 4);
                        return MAIN;
                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 211 "analizator.l"
{
                        printf("%d ~ if ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "if", "Cuvant rezervat", 5);
                        return IF;
                    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 216 "analizator.l"
{
                        printf("%d ~ else ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "else", "Cuvant rezervat", 6);
                        return ELSE;
                    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 221 "analizator.l"
{
                        printf("%d ~ while ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "while", "Cuvant rezervat", 7);
                        return WHILE;
                    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 226 "analizator.l"
{
                        printf("%d ~ cin ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "cin", "Cuvant rezervat", 8);
                        return CIN;
                    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 231 "analizator.l"
{
                        printf("%d ~ cout ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "cout", "Cuvant rezervat", 9);
                        return COUT;
                    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 236 "analizator.l"
{
                        printf("%d ~ struct ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "struct", "Cuvant rezervat", 10);
                        return STRUCT;
                    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 241 "analizator.l"
{
                        printf("%d ~ cattimp ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "cattimp", "Cuvant rezervat", 31);
                        return CATTIMP;
                    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 246 "analizator.l"
{
                        printf("%d ~ sfcattimp ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "sfcattimp", "Cuvant rezervat", 33);
                        return SFCATTIMP;
                    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 251 "analizator.l"
{
                        printf("%d ~ executa ~ Cuvant rezervat\n", line_ct); 
                        addAtom(line_ct, "executa", "Cuvant rezervat", 32);
                        return EXECUTA;
                    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 256 "analizator.l"
{
                        printf("%d ~ %s ~ Variabila\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Variabila", 0);
                        return ID_SIMPLU;
                    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 261 "analizator.l"
{
                        printf("%d ~ %s ~ Variabila\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Variabila", 0);
                        return ID;
                    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 266 "analizator.l"
{
                        printf("%d ~ %s ~ Constanta\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Constanta", 1);
                        return CONST_FLOAT;
                    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 271 "analizator.l"
{
                        printf("%d ~ %s ~ Constanta\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Constanta", 1);
                        return CONST_FLOAT;
                    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 276 "analizator.l"
{
                        printf("%d ~ %s ~ Constanta\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Constanta", 1);
                        return CONST_INT;
                    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 281 "analizator.l"
{
                        printf("%d ~ %s ~ Constanta\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Constanta", 1);
                        return CONST_INT;
                    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 286 "analizator.l"
{
                        printf("%d ~ %s ~ Constanta\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Constanta", 1);
                        return CONST_INT;
                    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 291 "analizator.l"
{
                        printf("%d ~ %s ~ Constanta\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Constanta", 1);
                        return CONST_INT;
                    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 296 "analizator.l"
{
                        printf("%d ~ >> ~ Operator\n", line_ct); 
                        addAtom(line_ct, ">>", "Operator", 11);
                        return OP_INP;
                    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 301 "analizator.l"
{
                        printf("%d ~ << ~ Operator\n", line_ct); 
                        addAtom(line_ct, "<<", "Operator", 12);
                        return OP_OUT;
                    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 306 "analizator.l"
{
                        printf("%d ~ + ~ Operator\n", line_ct); 
                        addAtom(line_ct, "+", "Operator", 13);
                        return PLUS;
                    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 311 "analizator.l"
{
                        printf("%d ~ - ~ Operator\n", line_ct); 
                        addAtom(line_ct, "-", "Operator", 14);
                        return MINUS;
                    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 316 "analizator.l"
{
                        printf("%d ~ * ~ Operator\n", line_ct); 
                        addAtom(line_ct, "*", "Operator", 15);
                        return INMUL;
                    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 321 "analizator.l"
{
                        printf("%d ~ / ~ Operator\n", line_ct); 
                        addAtom(line_ct, "/", "Operator", 16);
                        return DIV;
                    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 326 "analizator.l"
{
                        printf("%d ~ %% ~ Operator\n", line_ct); 
                        addAtom(line_ct, "%", "Operator", 17);
                        return MOD;
                    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 331 "analizator.l"
{
                        printf("%d ~ && ~ Operator\n", line_ct); 
                        addAtom(line_ct, "&&", "Operator", 18);
                        return AND;
                    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 336 "analizator.l"
{
                        printf("%d ~ || ~ Operator\n", line_ct); 
                        addAtom(line_ct, "||", "Operator", 19);
                        return OR;
                    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 341 "analizator.l"
{
                        printf("%d ~ < ~ Operator\n", line_ct); 
                        addAtom(line_ct, "<", "Operator", 20);
                        return MIC;
                    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 346 "analizator.l"
{
                        printf("%d ~ > ~ Operator\n", line_ct); 
                        addAtom(line_ct, ">", "Operator", 21);
                        return MARE;
                    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 351 "analizator.l"
{
                        printf("%d ~ != ~ Operator\n", line_ct); 
                        addAtom(line_ct, "!=", "Operator", 22);
                        return DIFERIT;
                    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 356 "analizator.l"
{
                        printf("%d ~ == ~ Operator\n", line_ct); 
                        addAtom(line_ct, "==", "Operator", 23);
                        return EGAL_EGAL;
                    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 361 "analizator.l"
{
                        printf("%d ~ = ~ Operator\n", line_ct); 
                        addAtom(line_ct, "=", "Operator", 24);
                        return EGAL;
                    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 366 "analizator.l"
{
                        printf("%d ~ ( ~ Separator\n", line_ct); 
                        addAtom(line_ct, "(", "Separator", 25);
                        return PD;
                    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 371 "analizator.l"
{
                        printf("%d ~ ) ~ Separator\n", line_ct); 
                        addAtom(line_ct, ")", "Separator", 26);
                        return PI;
                    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 376 "analizator.l"
{
                        printf("%d ~ { ~ Separator\n", line_ct); 
                        addAtom(line_ct, "{", "Separator", 27);
                        return AD;
                    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 381 "analizator.l"
{
                        printf("%d ~ } ~ Separator\n", line_ct); 
                        addAtom(line_ct, "}", "Separator", 28);
                        return AI;
                    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 386 "analizator.l"
{
                        printf("%d ~ ; ~ Separator\n", line_ct); 
                        addAtom(line_ct, ";", "Separator", 29);
                        return PV;
                    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 391 "analizator.l"
{
                        printf("%d ~ , ~ Separator\n", line_ct); 
                        addAtom(line_ct, ",", "Separator", 30);
                        return VIRGULA;
                    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 396 "analizator.l"
{
                        printf("%d ~ %s ~ Eroare\n", line_ct, yytext); 
                        addAtom(line_ct, yytext, "Eroare", -1);
                    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 400 "analizator.l"
ECHO;
	YY_BREAK
#line 1453 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 166 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 166 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 165);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 400 "analizator.l"

/* cod utilizator */
/*int main(){
    strcpy(atomi[0].atom, "ID");
    atomi[0].poz = 0;

    strcpy(atomi[1].atom, "CONST");
    atomi[1].poz = 1;

    strcpy(atomi[2].atom, "int");
    atomi[2].poz = 2;

    strcpy(atomi[3].atom, "float");
    atomi[3].poz = 3;

    strcpy(atomi[4].atom, "main");
    atomi[4].poz = 4;

    strcpy(atomi[5].atom, "if");
    atomi[5].poz = 5;

    strcpy(atomi[6].atom, "else");
    atomi[6].poz = 6;

    strcpy(atomi[7].atom, "while");
    atomi[7].poz = 7;

    strcpy(atomi[8].atom, "cin");
    atomi[8].poz = 8;

    strcpy(atomi[9].atom, "cout");
    atomi[9].poz = 9;

    strcpy(atomi[10].atom, "struct");
    atomi[10].poz = 10;

    strcpy(atomi[11].atom, ">>");
    atomi[11].poz = 11;

    strcpy(atomi[12].atom, "<<");
    atomi[12].poz = 12;

    strcpy(atomi[13].atom, "+");
    atomi[13].poz = 13;

    strcpy(atomi[14].atom, "-");
    atomi[14].poz = 14;

    strcpy(atomi[15].atom, "*");
    atomi[15].poz = 15;

    strcpy(atomi[16].atom, "/");
    atomi[16].poz = 16;
    
    strcpy(atomi[17].atom, "%");
    atomi[17].poz = 17;

    strcpy(atomi[18].atom, "&&");
    atomi[18].poz = 18;

    strcpy(atomi[19].atom, "||");
    atomi[19].poz = 19;

    strcpy(atomi[20].atom, "<");
    atomi[20].poz = 20;

    strcpy(atomi[21].atom, ">");
    atomi[21].poz = 21;

    strcpy(atomi[22].atom, "!=");
    atomi[22].poz = 22;

    strcpy(atomi[23].atom, "==");
    atomi[23].poz = 23;

    strcpy(atomi[24].atom, "=");
    atomi[24].poz = 24;

    strcpy(atomi[25].atom, "(");
    atomi[25].poz = 25;

    strcpy(atomi[26].atom, ")");
    atomi[26].poz = 26;

    strcpy(atomi[27].atom, "{");
    atomi[27].poz = 27;

    strcpy(atomi[28].atom, "}");
    atomi[28].poz = 28;

    strcpy(atomi[29].atom, ";");
    atomi[29].poz = 29;

    strcpy(atomi[30].atom, ",");
    atomi[30].poz = 30;

    strcpy(atomi[31].atom, "cattimp");
    atomi[31].poz = 31;

    strcpy(atomi[32].atom, "executa");
    atomi[32].poz = 32;

    strcpy(atomi[33].atom, "sfcattimp");
    atomi[33].poz = 33;

    atomi_ct = 34;

	yylex();

    if (strlen(error) != 0) {
        printf("Eroare %s\n", error);
    } else {

        printf("\n");
        printf("Atomii sunt: \n\n");
        for(int i = 0; i < atomi_ct; i++) {
            printf("Atomul %s si poz %d\n", atomi[i].atom, atomi[i].poz);
        }

        printf("\n");
        printf("Tabela simboluri id-uri: \n\n");
        inorder(TS_ID);

        printf("\n");
        printf("Tabela simboluri constante: \n\n");
        inorder(TS_CONST);

        printf("\n");
        printf("FIP: \n\n");
        for(int i = 0 ; i < fip_ct; i++) {
            if (FIP[i].poz_speciala != -1) {
                printf("[%d,%d]\n", FIP[i].poz_normala, FIP[i].poz_speciala);
            } else {
                printf("%d\n", FIP[i].poz_normala);
            }
        }
    }

	return 0;
}*/
